---
- name: Crear servidor de Grafana
  hosts: grafana
  become: yes
  roles:
    - grafana
- name: 
  hosts: psql
  become: yes
  roles:
    - postgresql
    - remote
- name: Crear página de Wordpress
  hosts: wordpress
  become: yes
  roles:
    - nginx
    - wordpress
    - mariadb

