--- 
    - name: instalar MariaDB
      apt:
        name:
          - mariadb-server
          - python3-pymysql
          - python3-mysqldb
        state: latest
  
    - name: Iniciar MariaDB
      service:
        name: mariadb
        enabled: true
        state: started

    - name: Establecer contraseña para usuario root
      shell: mysql -u root --password=toor -e "select(1);"

    - name: Crear base de datos para WordPress
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: wordpress_db
        login_user: root
        login_password: toor
        login_host: localhost
        state: present

    - name: Crear usuario para la base de datos
      mysql_user:
        login_user: root
        login_password: toor
        state: present
        name: wpuser
        password: WordPress
        priv: 'wordpress_db.*:ALL,GRANT'
        login_unix_socket: /var/run/mysqld/mysqld.sock
