---
- hosts: host
  become: yes

  tasks:
    - name: "Upgradear paquetes"
      shell: apt-get -y upgrade

    - name: "Actualizar paquetes"
      shell: apt-get -y update

    - name: "Instalar nginx"
      shell: apt-get -y install nginx

    - name: "Instalar MariaDB"
      shell: apt-get -y install mariadb-server

    - name: "Habilitar MariaDB"
      shell: systemctl enable mariadb.service

   # - name: Update MariaDB root password
      #mysql_user: name=root host={{item}} password='toor'
     # with_items:
       # - 127.0.0.1
      #  - ::1
     #   - localhost

    #- name: Set ~/.my.cnf file
     # template: src=dotmy.cnf.j2 dest=/root/.my.cnf mode=0600

    #- name: Delete anonymous MySQL user
      #mysql_user: name="" host={{item}} state=absent
      #with_items:
     #   - localhost
    #    - "{{ansible_nodename}}"

   # - name: Delete Hostname based MySQL user
  #    mysql_user: name=root host="{{ansible_nodename}}" state=absent

#    - name: Remove MySQL test database
 #     mysql_db: name=test state=absent

    - name: "Instalar paquetes necesarios"
      apt: "name={{ item }} state=present"
      with_items:
        - php
        - php-cli
        - php-fpm
        - php-mysql
        - php-json
        - php-opcache
        - php-mbstring
        - php-xml
        - php-gd
        - php-curl

    - name: "Crear directorio"
      shell: mkdir -p /var/www/html/wordpress/public_html

    - name: "Copiar archivo de configuración"
      copy:
        src: /home/ansible/wordpress/wordpress.conf
        dest: /etc/nginx/sites-available

    - name: "Crear enlace simbolico"
      shell: cd /etc/nginx/sites-enabled && ln -s ../sites-available/wordpress.conf .

    - name: "Reiniciar nginx"
      shell: systemctl reload nginx

    - name: "Cambiar de directorio"
      shell: cd /var/www/html/wordpress/public_html

    - name: "Descargar Wordpress"
      shell: wget https://wordpress.org/latest.tar.gz

    - name: "Extraer ficheros"
      shell: tar -zxvf latest.tar.gz

    - name: "Mover ficheros"
      shell: mv wordpress/* .

    - name: "Eliminar"
      shell: rm -rf wordpress

    - name: "Cambiar propietario"
      shell: chown -R www-data:www-data *

    - name: "Cambiar permisos"
      shell: chmod -R 755 *

    - name: "Cambiar nomre de fichero"
      shell: mv wp-config-sample.php wp-config.php

    - name: "Copiar fichero de configuración de Wordpress"
      copy:
        src: /home/ansible/wordpress/wp-config.php
        dest: /var/www/html/wordpress/public_html
