- name: Instalar Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes
  notify:
    - Start grafana
    - Enable grafana
- name: Iniciar Grafana
  systemd:
    name: grafana-server
    state: started
- name: Start Grafana
  systemd:
    name: grafana-server
    enabled: yes
